#!/usr/bin/env ruby
# frozen_string_literal: true

#
# scripts/goal-attachment-get - Get a single attachment
#
# Usage: goal-attachment-get <goal_id> <attachment_id>
#
# Output: JSON {"ok": true, "id": ..., "name": ..., "body": ...}
# Exit code: 0 on success, 1 on failure
#

require 'json'
require 'net/http'
require 'optparse'

RALPH_PLANS_URL = ENV.fetch('RALPH_PLANS_URL', 'http://ralph-plans.localhost:8000')

def main
  OptionParser.new do |opts|
    opts.banner = <<~HELP
      Usage: goal-attachment-get <goal_id> <attachment_id>

      Get a single attachment (including body) for a pipeline goal.

      Arguments:
        goal_id        Goal ID (required)
        attachment_id  Attachment ID (required)

      Output:
        JSON {"ok": true, "id": ..., "goal_id": ..., "name": ..., "body": ..., "created_at": ...}

      Examples:
        goal-attachment-get 42 7
        goal-attachment-get 42 7 | jq '.body'
    HELP
  end.parse!

  goal_id = ARGV[0]&.to_i
  attachment_id = ARGV[1]&.to_i

  unless goal_id && goal_id > 0
    puts JSON.generate(ok: false, error: 'goal_id is required')
    exit 1
  end

  unless attachment_id && attachment_id > 0
    puts JSON.generate(ok: false, error: 'attachment_id is required')
    exit 1
  end

  uri = URI("#{RALPH_PLANS_URL}/goals/#{goal_id}/attachments/#{attachment_id}")
  resp = Net::HTTP.get_response(uri)
  result = JSON.parse(resp.body)

  puts JSON.generate(result)
  exit(result['ok'] ? 0 : 1)
rescue Errno::ECONNREFUSED
  puts JSON.generate(ok: false, error: "cannot connect to ralph-plans at #{RALPH_PLANS_URL}")
  exit 1
end

if __FILE__ == $PROGRAM_NAME
  begin
    main
  rescue Interrupt
    exit 130
  end
end
